import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

interface ExportOptions {
  title: string
  subtitle?: string
  content: string
  metadata?: Record<string, string>
  tables?: Array<{
    title: string
    headers: string[]
    rows: string[][]
  }>
}

export function exportToPDF(options: ExportOptions): void {
  const { title, subtitle, content, metadata, tables } = options

  const doc = new jsPDF()
  let yPos = 20

  // Header
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text(title, 20, yPos)
  yPos += 10

  if (subtitle) {
    doc.setFontSize(12)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(100, 100, 100)
    doc.text(subtitle, 20, yPos)
    yPos += 10
  }

  // Metadata section
  if (metadata) {
    yPos += 5
    doc.setFontSize(10)
    doc.setTextColor(80, 80, 80)
    Object.entries(metadata).forEach(([key, value]) => {
      doc.text(`${key}: ${value}`, 20, yPos)
      yPos += 6
    })
    yPos += 5
  }

  // Divider line
  doc.setDrawColor(200, 200, 200)
  doc.line(20, yPos, 190, yPos)
  yPos += 10

  // Main content
  doc.setFontSize(11)
  doc.setTextColor(0, 0, 0)
  doc.setFont('helvetica', 'normal')

  // Clean and format content
  const cleanContent = content
    .replace(/\[\[(.+?)\]\]/g, '[$1]') // Convert wikilinks to brackets
    .replace(/\*\*(.+?)\*\*/g, '$1') // Remove bold markdown
    .replace(/###? /g, '') // Remove heading markers

  const lines = doc.splitTextToSize(cleanContent, 170)

  // Handle page breaks
  lines.forEach((line: string) => {
    if (yPos > 280) {
      doc.addPage()
      yPos = 20
    }
    doc.text(line, 20, yPos)
    yPos += 6
  })

  // Add tables if provided
  if (tables && tables.length > 0) {
    tables.forEach((table) => {
      if (yPos > 260) {
        doc.addPage()
        yPos = 20
      }

      yPos += 10
      doc.setFontSize(12)
      doc.setFont('helvetica', 'bold')
      doc.text(table.title, 20, yPos)
      yPos += 10

      autoTable(doc, {
        head: [table.headers],
        body: table.rows,
        startY: yPos,
        theme: 'grid',
        headStyles: {
          fillColor: [59, 130, 246], // Blue
          textColor: [255, 255, 255],
          fontSize: 10
        },
        styles: {
          fontSize: 9,
          cellPadding: 3
        }
      })

      yPos = (doc as any).lastAutoTable.finalY + 10
    })
  }

  // Footer with timestamp
  const pageCount = (doc as any).internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(
      `Generated by AlphaBot V2 • ${new Date().toLocaleString()} • Page ${i} of ${pageCount}`,
      20,
      287
    )
  }

  // Download
  const filename = `alphabot-${title.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}.pdf`
  doc.save(filename)
}

// Specialized export functions for different content types

export function exportSynthesis(data: {
  title: string
  newsUrl: string
  entities: string[]
  contradictions: any[]
  contradictionScore: any
  synthesis: string
}): void {
  const metadata = {
    'Source': data.newsUrl,
    'Generated': new Date().toLocaleString(),
    'Entities Analyzed': data.entities.join(', '),
    'Contradiction Score': `${data.contradictionScore.score}/100 (${data.contradictionScore.signal})`,
    'Frameworks Applied': '403-page elite framework wiki'
  }

  let content = `## Synthesis\n\n${data.synthesis}\n\n`

  if (data.contradictions.length > 0) {
    content += `## Detected Contradictions\n\n`
    data.contradictions.forEach((c: any, idx: number) => {
      content += `${idx + 1}. **${c.framework}** (${c.author})\n`
      content += `   Contradiction: ${c.contradiction}\n`
      content += `   Confidence: ${c.confidence}%\n`
      content += `   Investment Signal: ${c.investmentImplication}\n\n`
    })
  }

  exportToPDF({
    title: 'Real-Time Synthesis',
    subtitle: data.title,
    content,
    metadata
  })
}

export function exportScenario(data: {
  scenario: string
  category: string
  analysis: string
}): void {
  const metadata = {
    'Scenario Category': data.category,
    'Generated': new Date().toLocaleString(),
    'Analysis Engine': 'Claude Sonnet 4.5 + 403-page wiki'
  }

  exportToPDF({
    title: 'Scenario Analysis',
    subtitle: 'Counterfactual "What If" Simulation',
    content: `## Scenario\n\n${data.scenario}\n\n## Analysis\n\n${data.analysis}`,
    metadata
  })
}

export function exportBacktest(data: any): void {
  const metadata = {
    'Thesis Author': data.author,
    'Test Period': `${data.testPeriod.start} to ${data.testPeriod.end}`,
    'Category': data.category,
    'Generated': new Date().toLocaleString()
  }

  const performanceTable = {
    title: 'Performance Metrics',
    headers: ['Metric', 'Value'],
    rows: [
      ['Total Return', `${data.performance.totalReturnPercent >= 0 ? '+' : ''}${data.performance.totalReturnPercent.toFixed(1)}%`],
      ['Win Rate', `${data.performance.winRate.toFixed(0)}%`],
      ['Max Drawdown', `${data.performance.maxDrawdown.toFixed(1)}%`],
      ['Benchmark', data.vsIndex.benchmark],
      ['Benchmark Return', `${data.vsIndex.benchmarkReturn >= 0 ? '+' : ''}${data.vsIndex.benchmarkReturn.toFixed(1)}%`],
      ['Alpha', `${data.vsIndex.alpha >= 0 ? '+' : ''}${data.vsIndex.alpha.toFixed(1)}%`],
      ['Sharpe Ratio', data.performance.sharpeRatio?.toFixed(2) || 'N/A'],
      ['Outcome', data.outcome.toUpperCase()]
    ]
  }

  const tradesTable = {
    title: 'Trade History',
    headers: ['Ticker', 'Action', 'Entry', 'Exit', 'P&L', 'Return %'],
    rows: data.performance.trades.map((t: any) => [
      t.ticker,
      t.action,
      `$${t.entryPrice}`,
      t.exitPrice ? `$${t.exitPrice}` : 'Open',
      t.pnl ? `$${t.pnl.toLocaleString()}` : '-',
      t.pnlPercent ? `${t.pnlPercent >= 0 ? '+' : ''}${t.pnlPercent.toFixed(1)}%` : '-'
    ])
  }

  const content = `## Thesis Prediction\n\n${data.prediction}\n\n## Category\n\n${data.category}\n\n## Test Period\n\n${data.testPeriod.start} to ${data.testPeriod.end}`

  exportToPDF({
    title: `Backtest: ${data.thesisName}`,
    subtitle: `By ${data.author}`,
    content,
    metadata,
    tables: [performanceTable, tradesTable]
  })
}

export function exportTemporalAnalysis(data: {
  source: string
  accuracy: number
  predictions: any[]
  categoryBreakdown: any
}): void {
  const metadata = {
    'Source': data.source.replace(/\[\[|\]\]/g, ''),
    'Overall Accuracy': `${data.accuracy.toFixed(1)}%`,
    'Total Predictions': data.predictions.length.toString(),
    'Generated': new Date().toLocaleString()
  }

  const predictionsTable = {
    title: 'Prediction History',
    headers: ['Date', 'Claim', 'Outcome', 'Accuracy'],
    rows: data.predictions.map((p: any) => [
      p.predictionDate || 'N/A',
      p.claim.substring(0, 60) + '...',
      p.outcome,
      `${p.accuracyScore}%`
    ])
  }

  const categoryTable = {
    title: 'Accuracy by Category',
    headers: ['Category', 'Accuracy %', 'Count'],
    rows: Object.entries(data.categoryBreakdown).map(([cat, acc]: [string, any]) => [
      cat,
      `${acc.toFixed(1)}%`,
      '-'
    ])
  }

  exportToPDF({
    title: 'Source Credibility Report',
    subtitle: data.source.replace(/\[\[|\]\]/g, ''),
    content: 'This report tracks historical predictions and outcomes to measure source accuracy over time.',
    metadata,
    tables: [predictionsTable, categoryTable]
  })
}
